import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer/footer";
import Navbar from "@/components/Navbar/navbar";
import CartProvider from "@/components/CartSidebar/cartProvider";
import { ToastContainer } from "react-toastify";
import { findUserId } from "@/constans/findUserId";

export const metadata: Metadata = {
  title: "E-Cars",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  const userId = await findUserId();

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <CartProvider>
            <Navbar userId={userId} />
            {children}
            <ToastContainer stacked />
            <Footer />
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
