import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer/footer";
import Navbar from "@/components/Navbar/navbar";
import CartProvider from "@/components/CartSidebar/cartProvider";
import { ToastContainer } from "react-toastify";
import { findUserId } from "@/constans/findUserId";

export const metadata: Metadata = {
  title: "E-Cars",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  const userId = await findUserId();

  // if (isUserId === null) {
  //   Login Girişi Yapılmamış
  //   console.log("Giriş yapılmadı.");
  // } else {
  //   Login girişi yapılmış
  //   console.log("Giriş yapıldı.");
  //   console.log(isUserId);
  //   Databaseden bu kullanıcının sepet ürünlerini getir
  //   const fetchCartItems = async (userId) => {
  //     Veritabanına bağlanma
  //     const db = "";
    
  //     Ürünleri sorgulama
  //     const sql = `SELECT * FROM products WHERE cart_id = ${userId}`;
  //     const results = await db.query(sql);
    
  //     Ürünleri işleme
  //     const cartItems = results.map((item) => ({
  //       id: item.id,
  //       name: item.name,
  //       price: item.price,
  //       price_id: item.price_id,
  //       quantity: item.quantity,
  //     }));
    
  //     Ürünleri sepete ekleme
  //     const { addItem } = useShoppingCart();
  //     cartItems.forEach((item) => addItem(item));
  //   };
  // }

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <CartProvider>
            <Navbar userId={userId} />
            {children}
            <ToastContainer stacked />
            <Footer />
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
